/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvailableCouponItem: typeof import('./src/components/AvailableCouponItem.vue')['default']
    AvailableCoupons: typeof import('./src/components/AvailableCoupons.vue')['default']
    CouponDetail: typeof import('./src/components/CouponDetail.vue')['default']
    CouponItem: typeof import('./src/components/CouponItem.vue')['default']
    OrderInfoTab: typeof import('./src/components/OrderInfoTab.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    OrderRefundTab: typeof import('./src/components/OrderRefundTab.vue')['default']
    OrderTimelineTab: typeof import('./src/components/OrderTimelineTab.vue')['default']
    ProfileEditor: typeof import('./src/components/ProfileEditor.vue')['default']
    RechargeRecordItem: typeof import('./src/components/RechargeRecordItem.vue')['default']
    RechargeRecords: typeof import('./src/components/RechargeRecords.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
  }
}
