/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvailableCouponItem: typeof import('./src/components/AvailableCouponItem.vue')['default']
    AvailableCoupons: typeof import('./src/components/AvailableCoupons.vue')['default']
    CouponDetail: typeof import('./src/components/CouponDetail.vue')['default']
    CouponItem: typeof import('./src/components/CouponItem.vue')['default']
    OrderInfoTab: typeof import('./src/components/OrderInfoTab.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    OrderRefundTab: typeof import('./src/components/OrderRefundTab.vue')['default']
    OrderTimelineTab: typeof import('./src/components/OrderTimelineTab.vue')['default']
    ProfileEditor: typeof import('./src/components/ProfileEditor.vue')['default']
    RechargeRecordItem: typeof import('./src/components/RechargeRecordItem.vue')['default']
    RechargeRecords: typeof import('./src/components/RechargeRecords.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanNotify: typeof import('vant/es')['Notify']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
